# Generated by Django 5.0.6 on 2024-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='niveau',
            field=models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('avancé', 'Avancé')], default='Débutant', max_length=20),
        ),
    ]
