# Generated by Django 5.0.6 on 2024-12-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercices', '0002_exercice_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='erreur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
