# Generated by Django 5.0.6 on 2024-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercices', '0003_soumission_erreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='partager',
            field=models.BooleanField(default=False),
        ),
    ]
