# Generated by Django 5.0.6 on 2024-12-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercices', '0004_soumission_partager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('IDE', 'Environnement de développement intégré'), ('LIB', 'Bibliothèque/Framework'), ('DB', 'Base de données'), ('OTH', 'Autres')], default='OTH', max_length=3)),
                ('est_public', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outils', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
