# Generated by Django 5.0.6 on 2024-12-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercices', '0005_outil'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='ennoce',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='solution_attendue',
            field=models.TextField(max_length=300),
        ),
    ]
