# Generated by Django 5.1 on 2024-10-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
