# Generated by Django 5.1 on 2024-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur')], default='Etudiant', max_length=20),
        ),
    ]
