# Generated by Django 5.0.6 on 2024-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_alter_utilisateur_email_alter_utilisateur_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Exclus', 'Exclus')], default='Etudiant', max_length=20),
        ),
    ]
