# Generated by Django 5.0.6 on 2024-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_alter_utilisateur_photo_alter_utilisateur_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseigant', 'Enseignant'), ('Exclus', 'Exclus')], default='Etudiant', max_length=20),
        ),
    ]
