# Generated by Django 5.0.6 on 2024-11-13 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 18, 46, 22, 676225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 18, 46, 22, 676225, tzinfo=datetime.timezone.utc)),
        ),
    ]
