# Generated by Django 5.0.6 on 2024-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_commentaire_id_alter_cours_id_alter_module_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='formations/couvertures/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
