# Generated by Django 5.0.6 on 2024-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_cours_image_couverture_alter_formation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='image_couverture',
        ),
        migrations.AddField(
            model_name='module',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='formations/couvertures/'),
        ),
    ]
