# Generated by Django 5.0.6 on 2024-12-04 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_cours_image_couverture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
