# Generated by Django 5.0.6 on 2024-12-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_alter_cours_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
        migrations.AddField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.cours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('choix_multiple', 'Choix Multiple'), ('vrai_faux', 'Vrai/Faux')], max_length=20),
        ),
    ]
