# Generated by Django 5.0.6 on 2024-12-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_remove_quiz_module_quiz_cours_alter_cours_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.cours'),
        ),
    ]
