# Generated by Django 5.0.6 on 2024-12-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_alter_quiz_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.cours'),
        ),
    ]
