# Generated by Django 5.0.6 on 2024-12-18 19:06

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0010_alter_quiz_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='commentaires_likes', to=settings.AUTH_USER_MODEL),
        ),
       
    ]
