# Generated by Django 5.0.6 on 2024-12-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_commentaire_likes_alter_commentaire_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='approuve',
            field=models.BooleanField(default=True),
        ),
    ]
