# Generated by Django 5.0.6 on 2024-12-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_commentaire_approuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formation.commentaire'),
        ),
    ]
