# Generated by Django 5.0.6 on 2024-12-19 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_alter_commentaire_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la référence', max_length=255)),
                ('lien', models.URLField(help_text='URL de la référence', max_length=500)),
                ('type_reference', models.CharField(choices=[('video', 'Vidéo'), ('document', 'Document'), ('lien_externe', 'Lien Externe')], help_text='Type de référence', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de création de la référence')),
                ('cours', models.ForeignKey(help_text='Cours associé à la référence', on_delete=django.db.models.deletion.CASCADE, related_name='references', to='formation.cours')),
            ],
        ),
    ]
