# Generated by Django 5.0.6 on 2024-12-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='reponseutilisateur',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='reponseutilisateur',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='ReponseUtilisateur',
        ),
    ]
