# Generated by Django 5.0.6 on 2024-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0015_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='est_publier',
            field=models.BooleanField(default=True),
        ),
    ]
