# Generated by Django 5.0.6 on 2024-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0016_formation_est_publier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='est_publier',
        ),
        migrations.AddField(
            model_name='cours',
            name='est_publier',
            field=models.BooleanField(default=True),
        ),
    ]
